# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 501dfcbb16d9f244d9365a6e2f0b0dcc76d1faa6d0593a96599fddf24ad03626b8c847cd337585d7f55f4b918c135eca00e5760fe2666a12c5536995894ec2c7

test:
  secret_key_base: f39808b50bebe65761b4b9f1bbf770a3d6b4c4f14a966e366d17ec1f89df1eea74bda420f6df01112f890408aa538ad8b334efd7a524da6974ac639eca8f5e11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
